#!/usr/bin/env python3
import glob
import os

listing = glob.glob('*.ipynb')

for file in listing:
        print(file)
        os.system('jupyter nbconvert --output-dir scripts --to script ' + str(file))

